### ISSUE TITLE
Project doesn't work with Flask 3.0.0

### ISSUE THREAD

**Issue by Ret2Me** [cyberdelia/flask-mysql#55]
Hi, 
in new Flask 3.0.0 authors decided to remove deprecated method _request_ctx_stack.
Unfortunately your flask-mysql use them what cause exception during booting.

**Comment by xerosine** [comment]
Yes, now both the initial try and the exception in lines 5 and 7 flag ImportError

**Comment by antgarhe** [comment]
Do you know any solution or alternative?

**Comment by xerosine** [comment]
> Do you know any solution or alternative?

I had to downgrade to the previous version of flask, 2.3.3 or so

**Comment by AntGarH** [comment]
Yes, that's a solution, but you lose the _benefits_ of the latest versions, if they have any...

**Comment by xerosine** [comment]
> Yes, that's a solution, but you lose the _benefits_ of the latest versions, if they have any...

True, but till the code is updated, that's pretty much the only way that I know of without using a different package

**Comment by NiTRoeSE** [comment]
I have exactly the same problem:
Flask 3+ and flask-mysqldb throw error:
`ImportError: cannot import name '_app_ctx_stack' from 'flask' (/usr/local/lib/python3.10/dist-packages/flask/__init__.py)`

Hope someone can help or fix flask-mysqldb to be compatible with flask3+.

Thanks in advanced!

**Comment by BOTcommander7** [comment]
Same here

**Comment by AlanBell** [comment]
looks like this is the new syntax to do the same thing
https://stackoverflow.com/questions/73349956/deprecationwarning-reque-st-ctx-stack-is-deprecated-and-will-be-removed-in-f

**Comment by uwe999** [comment]
maybe switching to https://pypi.org/project/Flask-MySQLdb/2.0.0/ is an option?

**Comment by LincolnKermit** [comment]
> > Do you know any solution or alternative?
> 
> I had to downgrade to the previous version of flask, 2.3.3 or so

Thanks, worked for me!
